### ISSUE TITLE
On-boarding display issues

### ISSUE THREAD

**Issue by alvesjtiago** [recall-photos/recall-ios#4]
A beta user reported the following display issues (screenshots) when testing the on-boarding process which I can't reproduce. These are the specs:

```
App Version: 1.0 (14)
Installed App Version: 1.0 (14)

Device Information:
Device: iPhone9,3
iOS Version: 12.2
```

![image1](https://user-images.githubusercontent.com/407470/55159107-477f2e80-5158-11e9-98b1-1f44005d3119.png)
![image2](https://user-images.githubusercontent.com/407470/55159117-4b12b580-5158-11e9-9410-837e238c9bc9.png)

**Comment by jackveiga** [comment]
I wasn't able to replicate the issue on my phone.

**Comment by alvesjtiago** [comment]
Closing this for now. If someone reports it again we'll try to understand how to replicate.

**Comment by andresousa** [comment]
![IMG_8708](https://user-images.githubusercontent.com/1278551/56377392-3af37080-6202-11e9-8cbf-ff47232c6a62.PNG)
![IMG_8707](https://user-images.githubusercontent.com/1278551/56377393-3af37080-6202-11e9-9dea-753d13f65227.PNG)
![IMG_8706](https://user-images.githubusercontent.com/1278551/56377394-3af37080-6202-11e9-9509-9babced16612.PNG)
iPhone SE

**Comment by alvesjtiago** [comment]
@andresousa it will be fixed on the next release! Thanks for reporting 👌

**Comment by andresousa** [comment]
👍
